name: CI/CD

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies and deploy
        run: |
          # Use full paths to the cloudbuild.yaml file
          gcloud auth activate-service-account --key-file=Backend/diesel-nova-412314-f081f0198711.json
          gcloud config set project diesel-nova-412314
          gcloud auth list
          
          for service_folder in Backend/*; do
            if [ -d "$service_folder" ] && [ "$(basename "$service_folder")" != "api-samples" ]; then
              service_name=$(basename "$service_folder")
              pip install -r "$service_folder/requirements.txt"
              cd "$service_folder"
              gcloud config set project diesel-nova-412314
              gcloud builds submit --config "$GITHUB_WORKSPACE/Backend/${service_name}/cloudbuild.yaml"
              cd "$GITHUB_WORKSPACE"
            fi
          done
          

