name: CI/CD

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Set up GCP Credentials
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "$GCP_SA_KEY" > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud config set project diesel-nova-412314

      - name: Install dependencies
        run: |
          for service_folder in Backend/*; do
            if [ -d "$service_folder" ] && [ "$(basename "$service_folder")" != "api-samples" ]; then
              pip install -r "$service_folder/requirements.txt"
            fi
          done

      - name: Deploy all services
        run: |
          gcloud app deploy Backend/rdf-service/rdf-service.yaml Backend/recommendation-service/recommendation-service.yaml Backend/user-profile-service/user-profile-service.yaml --quiet


